# Generated by Django 2.2 on 2020-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now=True, verbose_name='created_time')),
                ('modified_time', models.DateField(auto_now_add=True, verbose_name='modified_time')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('category', models.ManyToManyField(related_name='category', to='category.Category')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag', to='tag.Tag')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
