# Generated by Django 2.2 on 2020-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_time', models.DateField(auto_now=True, verbose_name='created_time')),
                ('modified_time', models.DateField(auto_now_add=True, verbose_name='modified_time')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='name')),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='tag_id')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
